
version: '3.4'
volumes:
  node_modules_client:
  node_modules_server:
  mongo_data:
  upload_store:

services:

  db:
    image: 'bitnami/mongodb:latest'
    restart: always
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE=stmary
    volumes:
      - mongo_data:/bitnami

  client:
    image: client
    build:
      context: client
    restart: always
    command: npm start
    volumes:
      - ./client:/usr/app
      - node_modules_client:/usr/app/node_modules

  server:
    image: server
    build:
      context: server
    restart: always
    links:
      - db
    environment:
      - ADMIN_PASSWORD
      - ADMIN_NUMBER
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE=stmary
    command: npm start
    volumes:
      - ./server:/usr/app
      - upload_store:/uploads-store
      - node_modules_server:/usr/app/node_modules
    depends_on:
      - db

  proxy:
    image: nginx:alpine
    ports:
      - 8321:80
    links:
      - server
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/var/www/html
      #- ./uploads-store:/var/www/uploads
    restart: always
    depends_on:
      - client
      - server
